### ISSUE TITLE
Implementing Authentication

### ISSUE THREAD

**Issue by dcarson1661** [koopjs/koop-auth-direct-file#25]
After adding the auth plugin "koop add provider @koopjs/auth-direct-file", koop core seems to fail. I've followed the step by step guide and have successfully used koop without implementing authentication, but haven't been able to get passed this. What am I missing? Console output below:

2023-10-30T02:10:44.000Z warn: Unrecognized plugin type: "undefined". Defaulting to provider.
C:\Users\dcars\DOCUME~1\Scripts\testKoop\node_modules\@koopjs\koop-core\src\data-provider\index.js:56
      .replace(/\s/g, '-')
       ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at new DataProvider (C:\Users\dcars\DOCUME~1\Scripts\testKoop\node_modules\@koopjs\koop-core\src\data-provider\index.js:56:8)
    at #registerProvider (C:\Users\dcars\DOCUME~1\Scripts\testKoop\node_modules\@koopjs\koop-core\src\index.js:87:26)
    at Koop.register (C:\Users\dcars\DOCUME~1\Scripts\testKoop\node_modules\@koopjs\koop-core\src\index.js:83:34)
    at C:\Users\dcars\DOCUME~1\Scripts\testKoop\src\index.js:11:8
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\dcars\DOCUME~1\Scripts\testKoop\src\index.js:10:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)

Node.js v20.8.0

**Comment by rgwozdz** [comment]
@dcarson1661 - Thanks for reaching out.  I'll see if I can reproduce.

**Comment by AndrewAdamson** [comment]
I've been getting the same thing today. Workaround seems to be to add the auth register manually to src/index.js

**Comment by rgwozdz** [comment]
Shoot, sorry, I had been in the middle of responding to this and then got side tracked.  

@AndrewAdamson is correct,  part of the problem is that the CLI doesn't appear to fully support the auth module registration.  But also, @dcarson1661,  note that you are not using the correct CLI command.  The auth-module isn't a `provider`, but you are using `add provider`.

**Comment by dcarson1661** [comment]
@AndrewAdamson  & @rgwozdz Thanks for the info! 

The readme states:
# Add this Auth plugin
koop add provider @koopjs/auth-direct-file

should it be "koop add auth @koopjs/auth-direct-file"?

@AndrewAdamson mind sharing your src/index.js?

**Comment by rgwozdz** [comment]
> should it be "koop add auth @koopjs/auth-direct-file"?

Yes, right, that's a mistake (apologies for that).  But actually, the usage with CLI should just be removed altogether until the CLI is updated to properly register it.

I'm looking into Koop auth right now as part of a different effort...it might be able to be modified slight to allow easier CLI registration support.

**Comment by dcarson1661** [comment]
@rgwozdz makes sense, thank you!

**Comment by rgwozdz** [comment]
Docs now updated.
